baseurl = "https://www.graphql-java.com"
languageCode = "en-us"
title = ""
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Andreas Marek"
theme = "timer-hugo"

[menu]
    # Navbar Menus
    [[menu.nav]]
        name    = "Blog"
        url     = "/blog"
        weight  = 5

[params]
    # Social accounts. Link to these accounts are displayed in the header and
    # footer.
    home = "Home"
    logo = "images/logo.png"
    dateFormat = "6 January 2006"

    twitter = "graphql_java"
    github = "graphql-java"
    # Google Analytics API key.
    ga_api_key = "UA-55733269-1"
    # Mixpanel API key.
    # mixpanel_api_key = "Your Mixpanel API key"
    # author = "Your Name"
    # avatar = "/andi.jpeg"
    # contact = "Your contact link (ex. mailto:foo@example.com)"
    # bio = "Your short bio"
    # Short subtitle/tagline. This is displayed in the header.
    # subtitle = "Short subtitle/tagline of your blog"
    themecolor = "#hexcolor" # Defines the tab color in Chrome for Android.

    [params.banner]
        enable  = true
        bgImage = "images/slider.jpg"
        heading = "Welcome to graphql-java.com"
        description = "This is the homepage of the GraphQL Java implementation"
        btn     = false

