baseurl = "https://www.graphql-java.com"
languageCode = "en-us"
title = ""
# Copyright notice. This is displayer in the footer.
copyright = "&copy; Andreas Marek"
theme = "hugo-sustain"
pygmentsUseClasses=true

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "documentation"
  identifier = "documentation"
  weight = 200
  url = "/documentation/latest/"
[[menu.main]]
  name = "contact"
  identifier = "contact"
  weight = 300
  url = "/contact/"
[[menu.main]]
  name = "about"
  identifier = "about"
  weight = 400
  url = "/about/"
