baseurl = "https://www.graphql-java.com"
languageCode = "en-us"
title = ""
theme = "hugo-sustain"
pygmentsUseClasses=true

[params]
  latestReleases = ["v9.6", "v13.0"]
  latestDocs = "v13"

## Main Menu
[[menu.main]]
  name = "blog"
  weight = 100
  identifier = "blog"
  url = "/blog/"
[[menu.main]]
  name = "tutorials"
  weight = 100
  identifier = "tutorials"
  url = "/tutorials/"
[[menu.main]]
  name = "documentation"
  identifier = "documentation"
  weight = 200
  url = "/documentation/latest/"
[[menu.main]]
  name = "contact"
  identifier = "contact"
  weight = 300
  url = "/contact/"
[[menu.main]]
  name = "about"
  identifier = "about"
  weight = 400
  url = "/about/"
